module InvalidServerlessCacheStateFault = InvalidServerlessCacheStateFault

module DisassociateGlobalReplicationGroupMessage =
  DisassociateGlobalReplicationGroupMessage

module DataStorageUnit = DataStorageUnit
module NoOperationFault = NoOperationFault
module FilterValueList = FilterValueList
module Filter = Filter
module RecurringCharge = RecurringCharge
module RecurringChargeList = RecurringChargeList
module ReservedCacheNode = ReservedCacheNode
module ReservedCacheNodeList = ReservedCacheNodeList
module ReservedCacheNodeMessage = ReservedCacheNodeMessage
module KinesisFirehoseDestinationDetails = KinesisFirehoseDestinationDetails
module CloudWatchLogsDestinationDetails = CloudWatchLogsDestinationDetails
module DestinationDetails = DestinationDetails
module AutomaticFailoverStatus = AutomaticFailoverStatus
module GlobalReplicationGroupMember = GlobalReplicationGroupMember
module GlobalReplicationGroupMemberList = GlobalReplicationGroupMemberList
module GlobalNodeGroup = GlobalNodeGroup
module GlobalNodeGroupList = GlobalNodeGroupList
module GlobalReplicationGroup = GlobalReplicationGroup
module GlobalReplicationGroupAlreadyExistsFault = GlobalReplicationGroupAlreadyExistsFault
module ECPUPerSecond = ECPUPerSecond
module DataStorage = DataStorage
module CacheUsageLimits = CacheUsageLimits
module ParameterNameValue = ParameterNameValue
module ParameterNameValueList = ParameterNameValueList
module ModifyCacheParameterGroupMessage = ModifyCacheParameterGroupMessage
module NodeUpdateInitiatedBy = NodeUpdateInitiatedBy
module PreferredOutpostArnList = PreferredOutpostArnList
module PreferredAvailabilityZoneList = PreferredAvailabilityZoneList
module ConfigureShard = ConfigureShard
module ReplicaConfigurationList = ReplicaConfigurationList
module IncreaseReplicaCountMessage = IncreaseReplicaCountMessage
module DeleteGlobalReplicationGroupResult = DeleteGlobalReplicationGroupResult
module UserGroupIdList = UserGroupIdList
module TransitEncryptionMode = TransitEncryptionMode
module StorageEncryptionType = StorageEncryptionType
module UserGroupsUpdateStatus = UserGroupsUpdateStatus
module SlotMigration = SlotMigration
module ReshardingStatus = ReshardingStatus
module LogType = LogType
module LogFormat = LogFormat
module DestinationType = DestinationType
module PendingLogDeliveryConfiguration = PendingLogDeliveryConfiguration
module PendingLogDeliveryConfigurationList = PendingLogDeliveryConfigurationList
module PendingAutomaticFailoverStatus = PendingAutomaticFailoverStatus
module ClusterMode = ClusterMode
module AuthTokenUpdateStatus = AuthTokenUpdateStatus
module ReplicationGroupPendingModifiedValues = ReplicationGroupPendingModifiedValues
module ReplicationGroupOutpostArnList = ReplicationGroupOutpostArnList
module Endpoint = Endpoint
module NodeGroupMember = NodeGroupMember
module NodeGroupMemberList = NodeGroupMemberList
module NodeGroup = NodeGroup
module NodeGroupList = NodeGroupList
module NetworkType = NetworkType
module MultiAZStatus = MultiAZStatus
module LogDeliveryConfigurationStatus = LogDeliveryConfigurationStatus
module LogDeliveryConfiguration = LogDeliveryConfiguration
module LogDeliveryConfigurationList = LogDeliveryConfigurationList
module IpDiscovery = IpDiscovery
module GlobalReplicationGroupInfo = GlobalReplicationGroupInfo
module EffectiveDurability = EffectiveDurability
module Durability = Durability
module DataTieringStatus = DataTieringStatus
module ClusterIdList = ClusterIdList
module ReplicationGroup = ReplicationGroup
module StartMigrationResponse = StartMigrationResponse
module DescribeEngineDefaultParametersMessage = DescribeEngineDefaultParametersMessage
module SecurityGroupMembership = SecurityGroupMembership
module SecurityGroupMembershipList = SecurityGroupMembershipList
module ScaleConfig = ScaleConfig
module CacheNodeIdsList = CacheNodeIdsList
module PendingModifiedValues = PendingModifiedValues
module NotificationConfiguration = NotificationConfiguration
module CacheSecurityGroupMembership = CacheSecurityGroupMembership
module CacheSecurityGroupMembershipList = CacheSecurityGroupMembershipList
module CacheParameterGroupStatus = CacheParameterGroupStatus
module CacheNode = CacheNode
module CacheNodeList = CacheNodeList
module CacheCluster = CacheCluster
module CacheClusterList = CacheClusterList
module NodeUpdateStatus = NodeUpdateStatus
module NodeGroupMemberUpdateStatus = NodeGroupMemberUpdateStatus
module NodeGroupMemberUpdateStatusList = NodeGroupMemberUpdateStatusList
module UserIdListInput = UserIdListInput
module ModifyUserGroupMessage = ModifyUserGroupMessage
module ListTagsForResourceMessage = ListTagsForResourceMessage
module InvalidSnapshotStateFault = InvalidSnapshotStateFault
module PurchaseReservedCacheNodesOfferingResult = PurchaseReservedCacheNodesOfferingResult
module CacheEngineVersion = CacheEngineVersion
module CacheEngineVersionList = CacheEngineVersionList
module CacheEngineVersionMessage = CacheEngineVersionMessage
module CacheClusterIdList = CacheClusterIdList
module NodeGroupUpdateStatus = NodeGroupUpdateStatus
module NodeGroupUpdateStatusList = NodeGroupUpdateStatusList
module Tag = Tag
module TagList = TagList
module CreateCacheParameterGroupMessage = CreateCacheParameterGroupMessage
module SlaMet = SlaMet
module CreateServerlessCacheSnapshotRequest = CreateServerlessCacheSnapshotRequest
module CacheClusterAlreadyExistsFault = CacheClusterAlreadyExistsFault
module InvalidCredentialsException = InvalidCredentialsException
module CacheSubnetGroupQuotaExceededFault = CacheSubnetGroupQuotaExceededFault
module ChangeType = ChangeType
module CacheNodeTypeSpecificValue = CacheNodeTypeSpecificValue
module CacheNodeTypeSpecificValueList = CacheNodeTypeSpecificValueList
module CacheNodeTypeSpecificParameter = CacheNodeTypeSpecificParameter
module CacheNodeTypeSpecificParametersList = CacheNodeTypeSpecificParametersList
module NodeTypeList = NodeTypeList
module DescribeCacheParametersMessage = DescribeCacheParametersMessage
module ReplicationGroupList = ReplicationGroupList
module ReplicationGroupMessage = ReplicationGroupMessage
module KeyList = KeyList
module RemoveTagsFromResourceMessage = RemoveTagsFromResourceMessage
module SubnetIdsList = SubnetIdsList
module SnapshotArnsList = SnapshotArnsList
module SecurityGroupIdsList = SecurityGroupIdsList
module CreateServerlessCacheRequest = CreateServerlessCacheRequest
module UnprocessedUpdateAction = UnprocessedUpdateAction
module UnprocessedUpdateActionList = UnprocessedUpdateActionList
module UpdateActionStatus = UpdateActionStatus
module ProcessedUpdateAction = ProcessedUpdateAction
module ProcessedUpdateActionList = ProcessedUpdateActionList
module UpdateActionResultsMessage = UpdateActionResultsMessage
module OutpostArnsList = OutpostArnsList
module AvailabilityZonesList = AvailabilityZonesList
module NodeGroupConfiguration = NodeGroupConfiguration
module NodeSnapshot = NodeSnapshot
module NodeSnapshotList = NodeSnapshotList
module DescribeCacheEngineVersionsMessage = DescribeCacheEngineVersionsMessage
module SubnetIdentifierList = SubnetIdentifierList
module OutpostMode = OutpostMode
module LogDeliveryConfigurationRequest = LogDeliveryConfigurationRequest
module LogDeliveryConfigurationRequestList = LogDeliveryConfigurationRequestList
module CacheSecurityGroupNameList = CacheSecurityGroupNameList
module AZMode = AZMode
module CreateCacheClusterMessage = CreateCacheClusterMessage
module Snapshot = Snapshot
module CreateSnapshotResult = CreateSnapshotResult
module CacheNodeUpdateStatus = CacheNodeUpdateStatus
module CopySnapshotMessage = CopySnapshotMessage
module SubnetOutpost = SubnetOutpost
module NetworkTypeList = NetworkTypeList
module AvailabilityZone = AvailabilityZone
module Subnet = Subnet
module SubnetList = SubnetList
module CacheSubnetGroup = CacheSubnetGroup
module CacheSubnetGroups = CacheSubnetGroups
module SourceType = SourceType
module Event = Event
module EventList = EventList
module EventsMessage = EventsMessage
module DeleteCacheSecurityGroupMessage = DeleteCacheSecurityGroupMessage
module ServiceUpdateType = ServiceUpdateType
module ServiceUpdateStatus = ServiceUpdateStatus
module ServiceUpdateSeverity = ServiceUpdateSeverity
module CacheNodeUpdateStatusList = CacheNodeUpdateStatusList
module UpdateAction = UpdateAction
module UpdateActionList = UpdateActionList
module UpdateActionsMessage = UpdateActionsMessage
module ReservedCacheNodesOffering = ReservedCacheNodesOffering
module ReservedCacheNodesOfferingList = ReservedCacheNodesOfferingList
module DisassociateGlobalReplicationGroupResult = DisassociateGlobalReplicationGroupResult
module DescribeCacheSubnetGroupsMessage = DescribeCacheSubnetGroupsMessage
module AuthenticationType = AuthenticationType
module Authentication = Authentication
module User = User
module UserList = UserList
module UpdateActionStatusList = UpdateActionStatusList
module TimeRangeFilter = TimeRangeFilter
module ServiceUpdateStatusList = ServiceUpdateStatusList
module ReplicationGroupIdList = ReplicationGroupIdList
module DescribeUpdateActionsMessage = DescribeUpdateActionsMessage

module ModifyReplicationGroupShardConfigurationResult =
  ModifyReplicationGroupShardConfigurationResult

module CreateSnapshotMessage = CreateSnapshotMessage
module ServerlessCacheConfiguration = ServerlessCacheConfiguration
module ServerlessCacheSnapshot = ServerlessCacheSnapshot
module ExportServerlessCacheSnapshotResponse = ExportServerlessCacheSnapshotResponse
module UGServerlessCacheIdList = UGServerlessCacheIdList
module SnapshotFeatureNotSupportedFault = SnapshotFeatureNotSupportedFault
module CreateCacheClusterResult = CreateCacheClusterResult
module DefaultUserRequired = DefaultUserRequired
module UserGroupNotFoundFault = UserGroupNotFoundFault
module InvalidUserStateFault = InvalidUserStateFault
module UserIdList = UserIdList
module UserGroupPendingChanges = UserGroupPendingChanges
module UGReplicationGroupIdList = UGReplicationGroupIdList
module UserGroup = UserGroup
module UserGroupList = UserGroupList
module DescribeReservedCacheNodesMessage = DescribeReservedCacheNodesMessage
module ServiceUpdate = ServiceUpdate
module ServiceUpdateList = ServiceUpdateList
module ModifyGlobalReplicationGroupResult = ModifyGlobalReplicationGroupResult
module APICallRateForCustomerExceededFault = APICallRateForCustomerExceededFault
module CopyServerlessCacheSnapshotResponse = CopyServerlessCacheSnapshotResponse
module ReplicationGroupNotUnderMigrationFault = ReplicationGroupNotUnderMigrationFault

module IncreaseNodeGroupsInGlobalReplicationGroupResult =
  IncreaseNodeGroupsInGlobalReplicationGroupResult

module CacheParameterGroup = CacheParameterGroup
module CreateCacheParameterGroupResult = CreateCacheParameterGroupResult
module BatchApplyUpdateActionMessage = BatchApplyUpdateActionMessage
module UserGroupIdListInput = UserGroupIdListInput
module NodeGroupsToRetainList = NodeGroupsToRetainList
module ReshardingConfiguration = ReshardingConfiguration
module ReshardingConfigurationList = ReshardingConfigurationList
module NodeGroupsToRemoveList = NodeGroupsToRemoveList

module ModifyReplicationGroupShardConfigurationMessage =
  ModifyReplicationGroupShardConfigurationMessage

module SnapshotQuotaExceededFault = SnapshotQuotaExceededFault
module GlobalNodeGroupIdList = GlobalNodeGroupIdList
module UserNotFoundFault = UserNotFoundFault
module TestMigrationResponse = TestMigrationResponse
module DescribeUserGroupsResult = DescribeUserGroupsResult
module EC2SecurityGroup = EC2SecurityGroup
module EC2SecurityGroupList = EC2SecurityGroupList
module ReservedCacheNodeQuotaExceededFault = ReservedCacheNodeQuotaExceededFault
module RemoveReplicasList = RemoveReplicasList
module RebootCacheClusterMessage = RebootCacheClusterMessage
module CacheSubnetGroupAlreadyExistsFault = CacheSubnetGroupAlreadyExistsFault
module CacheClusterMessage = CacheClusterMessage
module InvalidCacheClusterStateFault = InvalidCacheClusterStateFault
module SnapshotAlreadyExistsFault = SnapshotAlreadyExistsFault
module ServiceLinkedRoleNotFoundFault = ServiceLinkedRoleNotFoundFault
module RevokeCacheSecurityGroupIngressMessage = RevokeCacheSecurityGroupIngressMessage
module CacheSecurityGroup = CacheSecurityGroup
module DescribeEventsMessage = DescribeEventsMessage
module CreateGlobalReplicationGroupResult = CreateGlobalReplicationGroupResult

module ServerlessCacheSnapshotQuotaExceededFault =
  ServerlessCacheSnapshotQuotaExceededFault

module ServerlessCacheSnapshotNotFoundFault = ServerlessCacheSnapshotNotFoundFault
module AuthTokenUpdateStrategyType = AuthTokenUpdateStrategyType
module ResetCacheParameterGroupMessage = ResetCacheParameterGroupMessage
module RegionalConfiguration = RegionalConfiguration
module DecreaseReplicaCountMessage = DecreaseReplicaCountMessage
module TestFailoverNotAvailableFault = TestFailoverNotAvailableFault
module FailoverGlobalReplicationGroupResult = FailoverGlobalReplicationGroupResult
module DeleteUserGroupMessage = DeleteUserGroupMessage
module CustomerNodeEndpoint = CustomerNodeEndpoint
module CustomerNodeEndpointList = CustomerNodeEndpointList
module CopySnapshotResult = CopySnapshotResult
module TagNotFoundFault = TagNotFoundFault
module ClusterQuotaForCustomerExceededFault = ClusterQuotaForCustomerExceededFault
module DeleteReplicationGroupMessage = DeleteReplicationGroupMessage
module DescribeUsersResult = DescribeUsersResult
module DeleteServerlessCacheRequest = DeleteServerlessCacheRequest
module CacheSecurityGroupQuotaExceededFault = CacheSecurityGroupQuotaExceededFault
module CacheParameterGroupList = CacheParameterGroupList

module DescribeReservedCacheNodesOfferingsMessage =
  DescribeReservedCacheNodesOfferingsMessage

module CompleteMigrationResponse = CompleteMigrationResponse

module AuthorizeCacheSecurityGroupIngressMessage =
  AuthorizeCacheSecurityGroupIngressMessage

module RebalanceSlotsInGlobalReplicationGroupMessage =
  RebalanceSlotsInGlobalReplicationGroupMessage

module NodeGroupNotFoundFault = NodeGroupNotFoundFault
module ServerlessCacheNotFoundFault = ServerlessCacheNotFoundFault
module InvalidServerlessCacheSnapshotStateFault = InvalidServerlessCacheSnapshotStateFault
module ReservedCacheNodeAlreadyExistsFault = ReservedCacheNodeAlreadyExistsFault
module ServiceUpdatesMessage = ServiceUpdatesMessage

module DecreaseNodeGroupsInGlobalReplicationGroupResult =
  DecreaseNodeGroupsInGlobalReplicationGroupResult

module ServerlessCacheSnapshotAlreadyExistsFault =
  ServerlessCacheSnapshotAlreadyExistsFault

module GlobalReplicationGroupList = GlobalReplicationGroupList
module DescribeGlobalReplicationGroupsResult = DescribeGlobalReplicationGroupsResult
module ReservedCacheNodesOfferingNotFoundFault = ReservedCacheNodesOfferingNotFoundFault
module DescribeReplicationGroupsMessage = DescribeReplicationGroupsMessage
module SnapshotNotFoundFault = SnapshotNotFoundFault
module FailoverGlobalReplicationGroupMessage = FailoverGlobalReplicationGroupMessage
module DescribeServiceUpdatesMessage = DescribeServiceUpdatesMessage
module RegionalConfigurationList = RegionalConfigurationList
module SnapshotList = SnapshotList
module DescribeSnapshotsListMessage = DescribeSnapshotsListMessage
module ServiceUpdateNotFoundFault = ServiceUpdateNotFoundFault
module DeleteReplicationGroupResult = DeleteReplicationGroupResult
module DeleteCacheClusterMessage = DeleteCacheClusterMessage

module ServerlessCacheQuotaForCustomerExceededFault =
  ServerlessCacheQuotaForCustomerExceededFault

module FilterList = FilterList
module ModifyServerlessCacheRequest = ModifyServerlessCacheRequest
module ReservedCacheNodesOfferingMessage = ReservedCacheNodesOfferingMessage
module CreateGlobalReplicationGroupMessage = CreateGlobalReplicationGroupMessage
module CopyServerlessCacheSnapshotRequest = CopyServerlessCacheSnapshotRequest
module DescribeServerlessCacheSnapshotsRequest = DescribeServerlessCacheSnapshotsRequest
module CreateCacheSecurityGroupResult = CreateCacheSecurityGroupResult
module StartMigrationMessage = StartMigrationMessage
module Parameter = Parameter
module DescribeCacheParameterGroupsMessage = DescribeCacheParameterGroupsMessage
module CacheParameterGroupNameMessage = CacheParameterGroupNameMessage
module ModifyCacheClusterMessage = ModifyCacheClusterMessage
module CreateCacheSubnetGroupResult = CreateCacheSubnetGroupResult
module DeleteSnapshotMessage = DeleteSnapshotMessage
module RebootCacheClusterResult = RebootCacheClusterResult
module DeleteCacheSubnetGroupMessage = DeleteCacheSubnetGroupMessage
module ServerlessCache = ServerlessCache
module CreateServerlessCacheResponse = CreateServerlessCacheResponse
module DescribeUsersMessage = DescribeUsersMessage
module CacheSecurityGroups = CacheSecurityGroups
module CacheSecurityGroupMessage = CacheSecurityGroupMessage
module ModifyReplicationGroupResult = ModifyReplicationGroupResult
module ParametersList = ParametersList
module GlobalReplicationGroupNotFoundFault = GlobalReplicationGroupNotFoundFault
module InvalidCacheSecurityGroupStateFault = InvalidCacheSecurityGroupStateFault
module TestFailoverResult = TestFailoverResult
module DeleteGlobalReplicationGroupMessage = DeleteGlobalReplicationGroupMessage
module ServerlessCacheSnapshotList = ServerlessCacheSnapshotList
module UserGroupQuotaExceededFault = UserGroupQuotaExceededFault

module RebalanceSlotsInGlobalReplicationGroupResult =
  RebalanceSlotsInGlobalReplicationGroupResult

module ModifyReplicationGroupMessage = ModifyReplicationGroupMessage
module ServerlessCacheList = ServerlessCacheList
module CacheParameterGroupDetails = CacheParameterGroupDetails
module EngineDefaults = EngineDefaults
module DeleteServerlessCacheSnapshotResponse = DeleteServerlessCacheSnapshotResponse
module CacheSubnetGroupInUse = CacheSubnetGroupInUse
module ModifyCacheClusterResult = ModifyCacheClusterResult
module NodeQuotaForClusterExceededFault = NodeQuotaForClusterExceededFault
module SubnetNotAllowedFault = SubnetNotAllowedFault
module ReplicationGroupAlreadyExistsFault = ReplicationGroupAlreadyExistsFault
module AllowedNodeTypeModificationsMessage = AllowedNodeTypeModificationsMessage

module IncreaseNodeGroupsInGlobalReplicationGroupMessage =
  IncreaseNodeGroupsInGlobalReplicationGroupMessage

module InvalidGlobalReplicationGroupStateFault = InvalidGlobalReplicationGroupStateFault
module ModifyGlobalReplicationGroupMessage = ModifyGlobalReplicationGroupMessage
module DescribeSnapshotsMessage = DescribeSnapshotsMessage
module InvalidCacheParameterGroupStateFault = InvalidCacheParameterGroupStateFault
module InvalidARNFault = InvalidARNFault
module CacheParameterGroupNotFoundFault = CacheParameterGroupNotFoundFault
module DescribeUserGroupsMessage = DescribeUserGroupsMessage
module CacheClusterNotFoundFault = CacheClusterNotFoundFault
module PasswordListInput = PasswordListInput
module InputAuthenticationType = InputAuthenticationType
module AuthenticationMode = AuthenticationMode
module ModifyUserMessage = ModifyUserMessage
module InvalidParameterCombinationException = InvalidParameterCombinationException
module AuthorizeCacheSecurityGroupIngressResult = AuthorizeCacheSecurityGroupIngressResult
module DescribeServerlessCacheSnapshotsResponse = DescribeServerlessCacheSnapshotsResponse
module InvalidVPCNetworkStateFault = InvalidVPCNetworkStateFault
module SubnetInUse = SubnetInUse
module CreateServerlessCacheSnapshotResponse = CreateServerlessCacheSnapshotResponse
module TestMigrationMessage = TestMigrationMessage
module NodeGroupConfigurationList = NodeGroupConfigurationList
module BatchStopUpdateActionMessage = BatchStopUpdateActionMessage
module CacheSubnetQuotaExceededFault = CacheSubnetQuotaExceededFault
module AddTagsToResourceMessage = AddTagsToResourceMessage
module CreateCacheSecurityGroupMessage = CreateCacheSecurityGroupMessage
module UserAlreadyExistsFault = UserAlreadyExistsFault
module InvalidSubnet = InvalidSubnet
module InsufficientCacheClusterCapacityFault = InsufficientCacheClusterCapacityFault
module InvalidKMSKeyFault = InvalidKMSKeyFault
module DescribeServerlessCachesRequest = DescribeServerlessCachesRequest
module ServerlessCacheAlreadyExistsFault = ServerlessCacheAlreadyExistsFault
module DeleteSnapshotResult = DeleteSnapshotResult
module TagQuotaPerResourceExceeded = TagQuotaPerResourceExceeded
module InvalidParameterValueException = InvalidParameterValueException
module DescribeServerlessCachesResponse = DescribeServerlessCachesResponse
module DescribeEngineDefaultParametersResult = DescribeEngineDefaultParametersResult
module CreateCacheSubnetGroupMessage = CreateCacheSubnetGroupMessage
module CacheParameterGroupQuotaExceededFault = CacheParameterGroupQuotaExceededFault
module ReplicationGroupNotFoundFault = ReplicationGroupNotFoundFault
module CreateReplicationGroupMessage = CreateReplicationGroupMessage
module InvalidReplicationGroupStateFault = InvalidReplicationGroupStateFault

module DecreaseNodeGroupsInGlobalReplicationGroupMessage =
  DecreaseNodeGroupsInGlobalReplicationGroupMessage

module ReservedCacheNodeNotFoundFault = ReservedCacheNodeNotFoundFault
module ModifyCacheSubnetGroupMessage = ModifyCacheSubnetGroupMessage
module DeleteServerlessCacheResponse = DeleteServerlessCacheResponse
module RevokeCacheSecurityGroupIngressResult = RevokeCacheSecurityGroupIngressResult
module CreateUserGroupMessage = CreateUserGroupMessage
module CacheSecurityGroupAlreadyExistsFault = CacheSecurityGroupAlreadyExistsFault
module CacheSubnetGroupNotFoundFault = CacheSubnetGroupNotFoundFault
module DescribeCacheSecurityGroupsMessage = DescribeCacheSecurityGroupsMessage
module DeleteServerlessCacheSnapshotRequest = DeleteServerlessCacheSnapshotRequest
module TestFailoverMessage = TestFailoverMessage
module UserQuotaExceededFault = UserQuotaExceededFault
module AuthorizationAlreadyExistsFault = AuthorizationAlreadyExistsFault
module IncreaseReplicaCountResult = IncreaseReplicaCountResult

module PurchaseReservedCacheNodesOfferingMessage =
  PurchaseReservedCacheNodesOfferingMessage

module TagListMessage = TagListMessage

module NodeGroupsPerReplicationGroupQuotaExceededFault =
  NodeGroupsPerReplicationGroupQuotaExceededFault

module UserGroupAlreadyExistsFault = UserGroupAlreadyExistsFault
module NodeQuotaForCustomerExceededFault = NodeQuotaForCustomerExceededFault
module ExportServerlessCacheSnapshotRequest = ExportServerlessCacheSnapshotRequest
module DecreaseReplicaCountResult = DecreaseReplicaCountResult
module DeleteCacheParameterGroupMessage = DeleteCacheParameterGroupMessage
module CompleteMigrationMessage = CompleteMigrationMessage
module DuplicateUserNameFault = DuplicateUserNameFault
module CacheSecurityGroupNotFoundFault = CacheSecurityGroupNotFoundFault
module ModifyServerlessCacheResponse = ModifyServerlessCacheResponse
module CacheSubnetGroupMessage = CacheSubnetGroupMessage

module ReplicationGroupAlreadyUnderMigrationFault =
  ReplicationGroupAlreadyUnderMigrationFault

module DefaultUserAssociatedToUserGroupFault = DefaultUserAssociatedToUserGroupFault
module AuthorizationNotFoundFault = AuthorizationNotFoundFault
module DescribeGlobalReplicationGroupsMessage = DescribeGlobalReplicationGroupsMessage
module DeleteUserMessage = DeleteUserMessage
module DeleteCacheClusterResult = DeleteCacheClusterResult
module CacheParameterGroupAlreadyExistsFault = CacheParameterGroupAlreadyExistsFault
module ModifyCacheSubnetGroupResult = ModifyCacheSubnetGroupResult
module CreateUserMessage = CreateUserMessage
module CreateReplicationGroupResult = CreateReplicationGroupResult
module DescribeCacheClustersMessage = DescribeCacheClustersMessage
module CacheParameterGroupsMessage = CacheParameterGroupsMessage
module ListAllowedNodeTypeModificationsMessage = ListAllowedNodeTypeModificationsMessage
module InvalidUserGroupStateFault = InvalidUserGroupStateFault
