open Aws.BaseTypes

type t =
  | INVALID_CREDENTIALS
  | CLUSTER_NOT_FOUND
  | NETWORK_ERRORS
  | INTERNAL_ERROR
  | INSUFFICIENT_CLOUDHSM_HSMS
  | USER_LOCKED_OUT
  | USER_NOT_FOUND
  | USER_LOGGED_IN
  | SUBNET_NOT_FOUND
  | INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET
  | XKS_PROXY_ACCESS_DENIED
  | XKS_PROXY_NOT_REACHABLE
  | XKS_VPC_ENDPOINT_SERVICE_NOT_FOUND
  | XKS_PROXY_INVALID_RESPONSE
  | XKS_PROXY_INVALID_CONFIGURATION
  | XKS_VPC_ENDPOINT_SERVICE_INVALID_CONFIGURATION
  | XKS_PROXY_TIMED_OUT
  | XKS_PROXY_INVALID_TLS_CONFIGURATION

let str_to_t =
  [ "XKS_PROXY_INVALID_TLS_CONFIGURATION", XKS_PROXY_INVALID_TLS_CONFIGURATION
  ; "XKS_PROXY_TIMED_OUT", XKS_PROXY_TIMED_OUT
  ; ( "XKS_VPC_ENDPOINT_SERVICE_INVALID_CONFIGURATION"
    , XKS_VPC_ENDPOINT_SERVICE_INVALID_CONFIGURATION )
  ; "XKS_PROXY_INVALID_CONFIGURATION", XKS_PROXY_INVALID_CONFIGURATION
  ; "XKS_PROXY_INVALID_RESPONSE", XKS_PROXY_INVALID_RESPONSE
  ; "XKS_VPC_ENDPOINT_SERVICE_NOT_FOUND", XKS_VPC_ENDPOINT_SERVICE_NOT_FOUND
  ; "XKS_PROXY_NOT_REACHABLE", XKS_PROXY_NOT_REACHABLE
  ; "XKS_PROXY_ACCESS_DENIED", XKS_PROXY_ACCESS_DENIED
  ; "INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET", INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET
  ; "SUBNET_NOT_FOUND", SUBNET_NOT_FOUND
  ; "USER_LOGGED_IN", USER_LOGGED_IN
  ; "USER_NOT_FOUND", USER_NOT_FOUND
  ; "USER_LOCKED_OUT", USER_LOCKED_OUT
  ; "INSUFFICIENT_CLOUDHSM_HSMS", INSUFFICIENT_CLOUDHSM_HSMS
  ; "INTERNAL_ERROR", INTERNAL_ERROR
  ; "NETWORK_ERRORS", NETWORK_ERRORS
  ; "CLUSTER_NOT_FOUND", CLUSTER_NOT_FOUND
  ; "INVALID_CREDENTIALS", INVALID_CREDENTIALS
  ]

let t_to_str =
  [ XKS_PROXY_INVALID_TLS_CONFIGURATION, "XKS_PROXY_INVALID_TLS_CONFIGURATION"
  ; XKS_PROXY_TIMED_OUT, "XKS_PROXY_TIMED_OUT"
  ; ( XKS_VPC_ENDPOINT_SERVICE_INVALID_CONFIGURATION
    , "XKS_VPC_ENDPOINT_SERVICE_INVALID_CONFIGURATION" )
  ; XKS_PROXY_INVALID_CONFIGURATION, "XKS_PROXY_INVALID_CONFIGURATION"
  ; XKS_PROXY_INVALID_RESPONSE, "XKS_PROXY_INVALID_RESPONSE"
  ; XKS_VPC_ENDPOINT_SERVICE_NOT_FOUND, "XKS_VPC_ENDPOINT_SERVICE_NOT_FOUND"
  ; XKS_PROXY_NOT_REACHABLE, "XKS_PROXY_NOT_REACHABLE"
  ; XKS_PROXY_ACCESS_DENIED, "XKS_PROXY_ACCESS_DENIED"
  ; INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET, "INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET"
  ; SUBNET_NOT_FOUND, "SUBNET_NOT_FOUND"
  ; USER_LOGGED_IN, "USER_LOGGED_IN"
  ; USER_NOT_FOUND, "USER_NOT_FOUND"
  ; USER_LOCKED_OUT, "USER_LOCKED_OUT"
  ; INSUFFICIENT_CLOUDHSM_HSMS, "INSUFFICIENT_CLOUDHSM_HSMS"
  ; INTERNAL_ERROR, "INTERNAL_ERROR"
  ; NETWORK_ERRORS, "NETWORK_ERRORS"
  ; CLUSTER_NOT_FOUND, "CLUSTER_NOT_FOUND"
  ; INVALID_CREDENTIALS, "INVALID_CREDENTIALS"
  ]

let to_string e = Aws.Util.of_option_exn (Aws.Util.list_find t_to_str e)
let of_string s = Aws.Util.of_option_exn (Aws.Util.list_find str_to_t s)
let make v () = v

let parse xml =
  Aws.Util.option_bind (String.parse xml) (fun s -> Aws.Util.list_find str_to_t s)

let to_query v =
  Aws.Query.Value (Some (Aws.Util.of_option_exn (Aws.Util.list_find t_to_str v)))

let to_json v = String.to_json (Aws.Util.of_option_exn (Aws.Util.list_find t_to_str v))
let of_json j = Aws.Util.of_option_exn (Aws.Util.list_find str_to_t (String.of_json j))
