open Aws.BaseTypes

type t =
  | CREATE_IN_PROGRESS
  | CREATE_FAILED
  | CREATE_COMPLETE
  | ROLLBACK_IN_PROGRESS
  | ROLLBACK_FAILED
  | ROLLBACK_COMPLETE
  | DELETE_IN_PROGRESS
  | DELETE_FAILED
  | DELETE_COMPLETE
  | UPDATE_IN_PROGRESS
  | UPDATE_COMPLETE_CLEANUP_IN_PROGRESS
  | UPDATE_COMPLETE
  | UPDATE_FAILED
  | UPDATE_ROLLBACK_IN_PROGRESS
  | UPDATE_ROLLBACK_FAILED
  | UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS
  | UPDATE_ROLLBACK_COMPLETE
  | REVIEW_IN_PROGRESS
  | IMPORT_IN_PROGRESS
  | IMPORT_COMPLETE
  | IMPORT_ROLLBACK_IN_PROGRESS
  | IMPORT_ROLLBACK_FAILED
  | IMPORT_ROLLBACK_COMPLETE

let str_to_t =
  [ "IMPORT_ROLLBACK_COMPLETE", IMPORT_ROLLBACK_COMPLETE
  ; "IMPORT_ROLLBACK_FAILED", IMPORT_ROLLBACK_FAILED
  ; "IMPORT_ROLLBACK_IN_PROGRESS", IMPORT_ROLLBACK_IN_PROGRESS
  ; "IMPORT_COMPLETE", IMPORT_COMPLETE
  ; "IMPORT_IN_PROGRESS", IMPORT_IN_PROGRESS
  ; "REVIEW_IN_PROGRESS", REVIEW_IN_PROGRESS
  ; "UPDATE_ROLLBACK_COMPLETE", UPDATE_ROLLBACK_COMPLETE
  ; ( "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS"
    , UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS )
  ; "UPDATE_ROLLBACK_FAILED", UPDATE_ROLLBACK_FAILED
  ; "UPDATE_ROLLBACK_IN_PROGRESS", UPDATE_ROLLBACK_IN_PROGRESS
  ; "UPDATE_FAILED", UPDATE_FAILED
  ; "UPDATE_COMPLETE", UPDATE_COMPLETE
  ; "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS", UPDATE_COMPLETE_CLEANUP_IN_PROGRESS
  ; "UPDATE_IN_PROGRESS", UPDATE_IN_PROGRESS
  ; "DELETE_COMPLETE", DELETE_COMPLETE
  ; "DELETE_FAILED", DELETE_FAILED
  ; "DELETE_IN_PROGRESS", DELETE_IN_PROGRESS
  ; "ROLLBACK_COMPLETE", ROLLBACK_COMPLETE
  ; "ROLLBACK_FAILED", ROLLBACK_FAILED
  ; "ROLLBACK_IN_PROGRESS", ROLLBACK_IN_PROGRESS
  ; "CREATE_COMPLETE", CREATE_COMPLETE
  ; "CREATE_FAILED", CREATE_FAILED
  ; "CREATE_IN_PROGRESS", CREATE_IN_PROGRESS
  ]

let t_to_str =
  [ IMPORT_ROLLBACK_COMPLETE, "IMPORT_ROLLBACK_COMPLETE"
  ; IMPORT_ROLLBACK_FAILED, "IMPORT_ROLLBACK_FAILED"
  ; IMPORT_ROLLBACK_IN_PROGRESS, "IMPORT_ROLLBACK_IN_PROGRESS"
  ; IMPORT_COMPLETE, "IMPORT_COMPLETE"
  ; IMPORT_IN_PROGRESS, "IMPORT_IN_PROGRESS"
  ; REVIEW_IN_PROGRESS, "REVIEW_IN_PROGRESS"
  ; UPDATE_ROLLBACK_COMPLETE, "UPDATE_ROLLBACK_COMPLETE"
  ; ( UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS
    , "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS" )
  ; UPDATE_ROLLBACK_FAILED, "UPDATE_ROLLBACK_FAILED"
  ; UPDATE_ROLLBACK_IN_PROGRESS, "UPDATE_ROLLBACK_IN_PROGRESS"
  ; UPDATE_FAILED, "UPDATE_FAILED"
  ; UPDATE_COMPLETE, "UPDATE_COMPLETE"
  ; UPDATE_COMPLETE_CLEANUP_IN_PROGRESS, "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS"
  ; UPDATE_IN_PROGRESS, "UPDATE_IN_PROGRESS"
  ; DELETE_COMPLETE, "DELETE_COMPLETE"
  ; DELETE_FAILED, "DELETE_FAILED"
  ; DELETE_IN_PROGRESS, "DELETE_IN_PROGRESS"
  ; ROLLBACK_COMPLETE, "ROLLBACK_COMPLETE"
  ; ROLLBACK_FAILED, "ROLLBACK_FAILED"
  ; ROLLBACK_IN_PROGRESS, "ROLLBACK_IN_PROGRESS"
  ; CREATE_COMPLETE, "CREATE_COMPLETE"
  ; CREATE_FAILED, "CREATE_FAILED"
  ; CREATE_IN_PROGRESS, "CREATE_IN_PROGRESS"
  ]

let to_string e = Aws.Util.of_option_exn (Aws.Util.list_find t_to_str e)
let of_string s = Aws.Util.of_option_exn (Aws.Util.list_find str_to_t s)
let make v () = v

let parse xml =
  Aws.Util.option_bind (String.parse xml) (fun s -> Aws.Util.list_find str_to_t s)

let to_query v =
  Aws.Query.Value (Some (Aws.Util.of_option_exn (Aws.Util.list_find t_to_str v)))

let to_json v = String.to_json (Aws.Util.of_option_exn (Aws.Util.list_find t_to_str v))
let of_json j = Aws.Util.of_option_exn (Aws.Util.list_find str_to_t (String.of_json j))
